# Generated by Django 4.2.4 on 2023-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_slug_alter_blog_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='to_published',
            field=models.BooleanField(verbose_name='Опубликовать?'),
        ),
    ]
